[package]
name = "poise-shuttle-bot-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
poise = "0.6.1"
shuttle-runtime = "0.45.0"
shuttle-serenity = "0.45.0"
tracing = "0.1.37"
tokio = "1.26.0"
